server:
  port: 9000

spring:
  datasource:
#    url: jdbc:mysql://www.kzj666.cn:3306/jumei?userUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&userSSL=false
    url: jdbc:mysql://localhost:3306/jumei?userUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&userSSL=false
    username: root
#    password: 123456
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    password: 123456
    database: 0
    host: 47.112.225.43
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 10
        max-wait: 1000ms


mybatis-plus:
  type-aliases-package: com.kk.entity
  mapper-locations: classpath:mapper/*.xml
